services:
  db:
    profiles: ["all", "without_loki", "db_only"]
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  opentelemetry-collector:
    profiles: ["all", "without_loki"]
    image: otel/opentelemetry-collector-contrib:0.116.1
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
      - ./exporters/logs:/exporters/logs
      - ./exporters/metrics:/exporters/metrics
    command:
      - '--config=/etc/otel/config.yaml'
    ports:
      - "4318:4318" # HTTP receiver

  loki:
    profiles: ["all"]
    image: grafana/loki:3.3.2
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    profiles: ["all", "without_loki"]
    image: grafana/grafana:11.4.0
    volumes:
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - "3000:3000/tcp"

  prometheus:
    profiles: ["all", "without_loki"]
    image: prom/prometheus:v3.1.0
    volumes:
      - "./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml"
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yaml"
    ports:
      - 9090:9090