receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  file/logs:
    path: /exporters/logs/file.json
#  otlp/logs:
#    endpoint: "http://loki:3100/otlp"
#    tls:
#      insecure: true
  file/metrics:
    path: /exporters/metrics/file.json
  prometheus/metrics:
    endpoint: 0.0.0.0:9464

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics, prometheus/metrics]
