spring:
  application:
    name: "notification-service"
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT}/notification_db"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    pool:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
          - metrics
  defaults:
    metrics:
      export:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: true
        url: "http://localhost:4318/v1/metrics"

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui"

otel:
  sdk:
    disabled: true
  instrumentation:
    common:
      default-enabled: false
    spring-webflux:
      enabled: true
    r2dbc:
      enabled: true
    log4j-appender:
        enabled: true
  metrics:
    exporter: otlp

logging:
  level:
    org:
      springframework:
        r2dbc: "INFO"
      kybprototyping: "DEBUG"

ports:
  notification-template-repository:
    impl: "jooq"