spring:
  application:
    name: "notification-service"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui"

logging:
  level:
    org:
      springframework:
        r2dbc: "DEBUG"
      kybprototyping: "DEBUG"

db:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  poolMaxSize: 5