spring:
  application:
    name: "notification-service"
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT}/notification_db"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    pool:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui"

logging:
  level:
    org:
      springframework:
        r2dbc: "DEBUG"
      kybprototyping: "DEBUG"


ports:
  notification-template-repository:
    impl: "spring-data"