spring:
  application:
    name: "notification-service"
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT}/notification_db"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    pool:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui"

otel:
  instrumentation:
    common:
      default-enabled: false
    spring-webflux:
      enabled: false
    r2dbc:
      enabled: false
    log4j-appender:
        enabled: true

logging:
  level:
    org:
      springframework:
        r2dbc: "INFO"
      kybprototyping: "DEBUG"

ports:
  notification-template-repository:
    impl: "spring-data"