spring:
  application:
    name: "notification-service"

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  poolMaxSize: ${DB_POOL_MAX_SIZE}